---
## site information
# name and siteurl
name: {en: Chenlin Wang, cn: 王琛林}
url: http://chenlin.me
# Time Zone
timezone: Asia/Shanghai
# Encoding
encoding: utf-8

## Conversion
markdown: redcarpet
redcarpet:
 extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter: pygments
